### ISSUE TITLE
Valid element nesting

### ISSUE THREAD

**Issue by stefnotch** [w3c/mathml-core#111]
I've been attempting to generate valid caret locations for any given MathML (see https://github.com/mjakeman/lasem/issues/11#issuecomment-991634611 ). However, one question that came up for me is which MathML elements can contain multiple children. 

For example
- Illegal: `<msup><mn>0</mn><mn>1</mn><mn>2</mn></msup>`
- Don't know: `<mn><mn>3</mn><mn>3</mn></mn>`
- Apparently legal: `<msqrt><mn>3</mn><mn>3</mn> </msqrt>`

The specification doesn't seem to have an obvious answer, but I'm guessing that I'm simply overlooking something.

**Comment by dginev** [comment]
@stefnotch isn't this a distinction of [inferred mrows](https://www.w3.org/TR/MathML3/chapter3.html#presm.inferredmrow) which can be resolved by looking at the [table of argument requirements](https://www.w3.org/TR/MathML3/chapter3.html#id.3.1.3.2) ?

**Comment by stefnotch** [comment]
@dginev Thank you very much, this lovely table is exactly what I've been searching for. 

I've been exclusively looking at the MathML Core specification, since it's so much simpler and seems to be the way forward. It might be worthwhile to add such a table there or link to it?

**Comment by davidcarlisle** [comment]
@stefnotch  the core spec doesn't use the language of "inferred mrows" I think partly to avoid any suggestion that the implementation should generate the extra mrows  in the resulting dom tree. It does however contain a phrase such as

> The children of the `<msqrt>` element are laid out using the algorithm of the `<mrow>` element

for each affected element specifying that (apart from the radical decoration) msqrt is treated by the math layout like mrow.

**Comment by NSoiffer** [comment]
Speaking personally and not as the chair of the WG, I feel the core spec is
aimed at implementers of MathML. The full spec is aimed a little more at
those using MathML and hence the extra info about number of arguments is
more appropriate there. The full spec has not been modified yet (we are
behind schedule on that), but the plan is that rather than duplicating
core, much of what is currently in chapter 3 will simply point off to core
where appropriate and highlight differences when something is not in core
(level 0) -- there are plans for multiple levels much as CSS has multiple
levels.

**Comment by stefnotch** [comment]
Sounds like a solid plan, thank you very much for all your excellent answers!

**Comment by fred-wang** [comment]
In MathML Core, there is not any notion of "illegal number of children" or "invalid markup" or "inferred mrow", any MathML element can contain any number of children and the spec (should) always indicates how to perform the layout, instead of leaving this undefined or up to implementers. However, some of these layout rules correspond to fallback mechanism motivated by the corresponding notions from MathML full. Maybe we can add an informative paragraph in section 2. to clarify this.

As for your examples:

* `<msup><mn>0</mn><mn>1</mn><mn>2</mn></msup>`: The spec says "If the `<msub>` element has less or more than two in-flow children, its layout algorithm is the same as the `<mrow>` element." and the layout of `<mrow>` does not have any restriction on children.
* `<mn><mn>3</mn><mn>3</mn></mn>`: The HTML5 parser may prevent this (would need to check the WHATWG spec) but you can definitely produce this via DOM operations. The spec says "Its layout algorithm is the same as the `<mtext>` element." and the layout of `<mtext>` does not have any restriction on children.
* `<msqrt><mn>3</mn><mn>3</mn></msqrt>`: as David mentioned, the radical section handles this case explicitly.
