### ISSUE TITLE
MathML-Core meeting, Monday April 25, 2022 Agenda

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#143]
Only one agenda agenda item this week, and no updates I think we need to share.  I think we are also going to have a few people out.  Might be a quick one -- feel free to reply to suggest more.

* Implementation report/WPT integrations #119 https://github.com/w3c/mathml-core/issues/119

**Comment by dginev** [comment]
* Question for the meeting: We have 4 issues with the `Agenda` label, visible at ["issue open; label Agenda"](https://github.com/w3c/mathml-core/issues?q=is%3Aissue+is%3Aopen+label%3AAgenda).
    *  I recall #52 and #70 were close to resolved during the group discussions. Are they ready?
    *  #38 may simply need the label removed, and
    *  #104 doesn't have a clear note on what is the condition to close - maybe it's also close-able?

**Comment by NSoiffer** [comment]
#52: As much as I don't like it, we agreed to remove mo@accent because it seems most software doesn't generate it and David Cervone at Mathjax agreed to drop MathJaX from generating it. I will close it.

#70: We agree that "-" needs to be transformed into hyphen-minus and that if Igalia's implementation doesn't support it, that should be a test failure. The Jan minutes say we will discuss this later, but I can't find where we said it should be done. It is supported by Safari and Firefox. I just added a needs-test label. I guess we need to formally minute this and add that to a comment.

#104: This is done. I'll close it.

#38 is level 2, so no need to talk about it now.

**Comment by NSoiffer** [comment]
We need to update the WD of core -- it is suppose to be updated within six months, move it to CR, or it dies.

**Comment by davidcarlisle** [comment]
Could also perhaps  discuss a github actions workflow cf  w3c/mathml#329 which is down as an issue against the full spec but applies to Core as well.
