### ISSUE TITLE
Update MathML links in the WHATWG specification

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#150]
These are currently pointing to MathML3, but should most likely point to core - for example, currently  https://www.w3.org/Math/draft-spec/chapter2.html#interf.toplevel

**Comment by davidcarlisle** [comment]
In general I'd _like_ to agree with this but it again raises the issue of attributes not currently mentioned in core.

In particular 
https://html.spec.whatwg.org/#elements-3
lists `<math>` and references the MathML(3) spec for conforming attributes.


> Whether the attributes in the table above are conforming or not is defined by other specifications (e.g. SVG 2 and MathML); this section only describes the syntax rules if the attributes are serialized using the HTML syntax.

Currently that could be updated to MathML4 draft, but if updated to reference Core (which would make more sense in many ways) it would make several attributes non-conforming, notably `alttext` which is problematic  as it is for example required on `<math>` used in the spec by W3C pubrules (as currently written).

Currently Core makes no mention of `alttext` but it is added by MathML4 full (and the schema in that spec) for use by systems that do not support MathML.

Personally I'd prefer that Core listed `alttext`  as a conforming attribute with a defined behaviour that it be ignored by applications supporting MathML.  (the `intent` attribute is currently handled in a similar way, not mentioned in Core, although `alttext` is easier as it only affects `<math>`)

**Comment by bkardell** [comment]
Do we know if `alttext` is actually exposed and used by anyone in any way?

**Comment by clapierre** [comment]
I know we had an advance EPUB test book that specifically tested this `alttext` within the MathML, but since we did't explicitly ask testers to test this feature it hasn't been reported.  I believe that the Read-Aloud features of a Reading system would use this attribute when the reading system reads to you without using a Screen Reader.

**Comment by davidcarlisle** [comment]
@bkardell  daisy at least seems to recommend it is added,

http://kb.daisy.org/publishing/docs/html/mathml.html#

which systems use it I am not so sure. In an ideal world all systems would ignore the text fallback and process the MathML but that may not be the world we live in.

**Comment by davidcarlisle** [comment]
@Steve-Noble I think you mentioned alttext being used in a zoom meeting no so long ago?

**Comment by bkardell** [comment]
I don't see how it can reasonably make sense for the WHATWG spec to point to anything but core, which means that indeed if people use anything beyond core and have some validator/checker that actually cares about non-standard attributes it will get flagged.  However for HTML this happens all the time and we just offer some checkboxes or ability to ignore some for different checkers. I don't know how we are going to overcome this as a 'larger' problem if full is going to continue to extend core this is just going to happen.

However, since you seem to be expressing concern about one very particular one (alttext) and since that  is just a simple (reflecting?) attribute and anything beyond that would be left up to additional specifications (like the AAM) I don't see a reason this would be particularly difficult to add to core -- would that will satisfy your concerns about linking?  Like, realistically, I think the only test we could write for it in core is "is it a reflecting attribute" (if it is supposed to be reflecting like alt is) that will have not much to do with with whether or not that will be used.  It's kind of unfortunate it isn't just `alt`

**Comment by NSoiffer** [comment]
As I mentioned today in #115, it isn't just ignoring the attr, it needs to get into the accessibility tree. So there could be a test for that. I don't know the details of how one tests that, but hopefully that is something testable. The same needs to happen with `intent` and `arg`.

**Comment by davidcarlisle** [comment]
@bkardell  another accessibility system currently using this is https://www.hawkeslearning.com/Accessibility/guides/mathml_intro.html (no personal experience,  just came up in search) I don't think we should make systems that are producing conforming documents be reclassified as producing non conforming documents by updating references to a spec that doesn't describe the attribute.

I agree that HTML should reference Core rather than Full, but  to make that work, Core should specify the conforming attributes on mathml used on the web, even if they don't affect the layout as specified in Core, so alttext and also intent and arg possibly also altimg as that is also required by daisy

http://www.daisy.org/z3986/structure/SG-DAISY3/part2-math.html#L2707

**Comment by davidcarlisle** [comment]
I think the recent changes to core address the issues here and we should make a PR against html

**Comment by bkardell** [comment]
I believe this was done with https://github.com/whatwg/html/pull/9804, closing
