### ISSUE TITLE
Applying visual effects

### ISSUE THREAD

**Issue by chrishtr** [w3c/mathml-core#162]
Has there been any discussion of what to do when transform, filter, opacity, blend-mode, clip-path, clip, etc are applied to a MathML element?

This is very related to the containing block and stacking context discussion (e.g. w3c/mathml-core#74).

**Comment by bkardell** [comment]
As resolved today in the meeting: We believe the issues referred to in the OP ( containing block and stacking context discussion) were fixed and that many tests have been added since. These visual effects should now just work, but if @chrishtr feels that we still need additional tests, please feel free to reopen.
