### ISSUE TITLE
Remove mathvariant from core (except 'normal')

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml-core#182]
I'm starting a new issue based on a side topic mentioned in #181:
> Regarding mathvariant, this is controversial because really only the automatic italicization of the single-char <mi> can be characterized as "stylistic". We failed to convince the CSS WG to extend text-transform for other attribute values, so we didn't implement them in chromium and a large amount of tests are failing. Googlers even suggested to remove this mathvariant thing to resolve that problem. My preference would be to just drop mathvariant from MathML Core (only keeping mathvariant="normal" on mi) and tell people to use proper Unicode code points instead.

The Math WG (full) discussed this today and the reluctant resolution is that now is a good time has come to get rid of `mathvariant` from core, especially since it sounds like it can't be supported in core.

`mathvariant="normal"` does need to be kept. It is a little strange to have an attribute with that name, but it, like many things in other languages, has that name because of history.

**Comment by dginev** [comment]
This may be an opportune place and time to ask early a connected question:

Are these two formulations identical in MathML Core + CSS, by default?
And are they *meant to be* identical?

```xml
<mi mathvariant="normal">x</mi>

<mi style="text-transform:none;">x</mi>
```

**Comment by NSoiffer** [comment]
I'll leave that question to @fred-wang to answer.

I just spotted that [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) includes `text-transform` values `math-auto`, `math-bold`, etc. As @fred-wang said, I thought these were rejected. Is MDN wrong or did I (we?) miss something?

What is different is `<mi style="font-style: normal">x</mi>`. `mathvariant` is saying I want U+1D431 where as the style change is getting the ASCII 'x'.

There is hopefully a WPT test to make sure that `style="font-style: italic"` doesn't change the character used for rendering when a char in the math alphanumeric block is used, explicitly or in the case of `mathvariant="normal"`, implicitly.

**Comment by fred-wang** [comment]
@dginev: Yes and yes for MathML Core, the spec says to treat mathvariant="normal" as a presentational hint `text-transform: none`: https://w3c.github.io/mathml-core/#the-mathvariant-attribute. However, WebKit and Firefox don't implement (automatic) mathvariant via `text-transform` yet, so we probably want to keep mathvariant="normal" for now anyway. Implementation-wise it is very small amount of code to map it to `text-transform: none`.

@NSoiffer MDN automatically parses the MathML Core spec to generate the documentation of formal definition/syntax but really the CSS WG only approved `math-auto`. So that's another reason to remove it ASAP and avoid misleading users with bad documentation when Chromium is released.

I didn't get what you mean but in MathML Core `font-style`/`font-weight` are totally orthogonal to `mathvariant`: the former properties specify the type of font used, the latter the unicode character used. Actually they were some hacks in Firefox to deal with conflicts with the legacy `fontstyle`/`fontweight` attributes, but they were causing more bugs and have been removed. So for example:

- `<mi style="font-style: normal">x</mi>` is normally the same as `<mi>x</mi>` which is rendered as U+1D431 taken from a normal font.
- `<mi style="font-style: italic">x</mi>` is rendered as U+1D431 taken from an italic font.
- `<mi style="font-weight: bold">x</mi>` is rendered as U+1D431 taken from a bold font.
- `<mi style="font-style: italic; font-weight: bold">x</mi>` is rendered as U+1D431 taken from a bold-italic font.
- `<mi style="font-style: normal">sin</mi>` is normally the same as `<mi>sin</mi>` which is rendered as ASCII "sin" with a normal font.
- `<mi style="font-style: italic">sin</mi>` is rendered as ASCII "sin" with an italic font.
- `<mi style="font-style: bold">sin</mi>` is rendered as ASCII "sin" with a bold font.
- `<mi style="font-style: italic; font-weight: bold">sin</mi>` is rendered as ASCII "sin" with a bold-italic font.
- `<mi style="font-style: italic; text-transform: none">x</mi>` is rendered as ASCII 'x' taken from an italic font.
- `<mi style="font-weight: bold; text-transform: uppercase">x</mi>` is rendered as ASCII 'X' taken from a bold font.
- etc

(they are more subtilities with font-weight/font-style, like they can probably try to programmatically italicize/boldify a glyph from the normal font if bold/italic/bold-italic fonts don't provide the proper glyph, or rely on a single variable font to perform these transformations, but again all of these is out of the scope of the MathML Core spec and is specified elsewhere)

**Comment by fred-wang** [comment]
I wonder what's the status of this? It's currently one of the biggest issue for https://github.com/web-platform-tests/interop/issues/197#issuecomment-1301912244

**Comment by dginev** [comment]
@fred-wang I believe as far as the WG was concerned, we resolved to remove `mathvariant` except for `mathvariant="normal"` on Dec 15th, and considered our job done.

Maybe the word "reluctant" in the description was misleading - there was group consensus to move forward with the removal. I am not aware of other WG activity since, except for our clarifying questions above. 

My guess is that the next step here is to make the changes to the Core text.

**Comment by fred-wang** [comment]
Spec updated.

We need to remove tests. However, WebKit/Firefox still implement the mathvariant attribute so they need to copy the tests in their internal suites.

**Comment by fred-wang** [comment]
Was the consensus to keep `mathvariant` as a global attribute (as in the current spec) or just an attribute for the mi element (as in my initial comment)?

**Comment by fred-wang** [comment]
I just submitted a PR to start updating the tests. But for attribute-mapping-002.html I need to know whether mathvariant would still be global or mi-specific.

**Comment by dginev** [comment]
> Was the consensus to keep mathvariant as a global attribute (as in the current spec) or just an attribute for the mi element (as in my initial comment)?

As far as I recall, we did not discuss a restriction to `mi`.

Maybe we could sneak that question in for this Thursday @NSoiffer ?

**Comment by NSoiffer** [comment]
Somewhere along the line I said it didn't make sense for it to be a global attr as it is very specific to the `mi` element. So I agree with @fred-wang initial inclination.

I can add this to the agenda for the meeting on Thursday.

**Comment by davidcarlisle** [comment]
> Somewhere along the line I said it didn't make sense for it to be a global attr as it is very specific to the `mi` element. So I agree with @fred-wang initial inclination.
> 
> I can add this to the agenda for the meeting on Thursday.

the unicode math alphabet blocks include digits so it's quite natural to use mathvariant on mn to get 𝟙 or whatever, and I've certainly used that in the past. But since the proposal is to only allow the value `normal` which is default anyway for mn it makes sense to restrict to mi at the same time.

**Comment by dginev** [comment]
@fred-wang the group discussed this today and we had consensus to accept your suggestion.

Namely, restrict `mathvariant` as an attribute only allowed on the `mi` element in MathML Core.
And we are still in agreement about `mathvariant=normal` as the only defined value.

**Comment by NSoiffer** [comment]
We discussed this at the meeting today and agreed that since `mathvariant='normal' if only useful on `mi`, it should be a local attr for it.

**Comment by fred-wang** [comment]
Thanks, I'll update the spec and test PR.

**Comment by bkardell** [comment]
Reviewing this in the meeting today, we think we can close this and trust that @fred-wang will correct us and reopen if we're wrong.
