### ISSUE TITLE
MathML Core Meeting Jan 30, 2023

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#185]
Agenda items, feel free to reply to suggest more, but I believe the majority of our call should be spent on CR / Rechartering and any notable issues in L1 that need cleaning up.

- Updates:
  - MathML Core Support Released on Chome 109 - did you miss it? Oh happy day!
- CR / Review
- Rechartering
- Notable Issues in L1?
  - [Deprecate <none> element in Core #173](https://github.com/w3c/mathml-core/issues/173#top) (closable?)
  - [Parsing of columnspan/rowspan #180 ](https://github.com/w3c/mathml-core/issues/180#top)
  - [Remove mathvariant from core (except 'normal') #182](https://github.com/w3c/mathml-core/issues/182)
  - [behavior of display: math on mainline HTML ? #176](https://github.com/w3c/mathml-core/issues/176)

**Comment by dginev** [comment]
Happy day indeed!

FYI #39, #78, #103, #164 and #183 have had observed practical impact since the Chrome 109 launch.
(i.e. user reports for the live demos touching on them, directly or indirectly)
But I fear none of them is easy enough to resolve on a short notice. Looks like a good place to at least bookmark the observation.

**Comment by NSoiffer** [comment]
I think #103 is important to add to the agenda because it is a difference from MathML 3/4 and thus needs to be discussed and resolved in the spec.
