### ISSUE TITLE
min-width for <mpadded>

### ISSUE THREAD

**Issue by ronkok** [w3c/mathml-core#202]
Currently in MathML-Core, one can set a `width` on an `<mpadded>` element, and I believe, only on an `<mpadded>` element. There seems to be no way to set a `min-width` on any MathML element, `<mpadded>` or otherwise.

This makes it difficult to emulate the behavior of LaTeX extensible arrows, all of which have a minimum width.

This issue proposes to add a `min-width` to the specification of the `<mpadded>` element.

**Comment by dginev** [comment]
I have a connected question I'd like to clarify:
Currently, Chrome (but not Firefox) respects the CSS `min-width` property on (all? most?) MathML Core elements.

For example:
```html
<math>
  <mrow style="min-width:100px; background-color:green;">
    <mi>x</mi>
  </mrow>
</math>
```

Is that use of CSS to be encouraged or discouraged? Thanks.

**Comment by NSoiffer** [comment]
@ronkok: it seems your reason for your proposal is to be able to emulate extensible arrows in LaTeX. Doesn't `<mo>`s `minsize` attr allow you to do this? 

I also want to note (it may be obvious, sorry) that a CSS min-width won't cause stretching, is just sets the minimum width of the element... at least in the chromium-based browsers that have implemented MathML-core's requirements wrt to CSS.

**Comment by ronkok** [comment]
I currently have a work-around for extensible arrows. It's a horrible kludge, and I would very much like to use a `minsize` or a `min-width` instead. But it is working, so this issue is perhaps less of a priority than some other issues.

**Comment by ronkok** [comment]
Just to tie up some loose ends: I've just done a test and the `minsize` attribute currently has no effect on horizontal operators, either in Chromium or Gecko. However, issue #64 has a "level-2" label. I take that to mean it is planned for future implementation.

If/when `minsize` is implemented, that would indeed make this issue unnecessary. To avoid duplication, I'm going to close this issue, continue operating with my current horrible kludge workaround, and hope that `minsize` will eventually be implemented for horizontal stretchy operators.

**Comment by dginev** [comment]
To also address my question for archival:
> Currently, Chrome (but not Firefox) respects the CSS min-width property on (all? most?) MathML Core elements.
> Is that use of CSS to be encouraged or discouraged? Thanks.

I think the prevailing sentiment in the last couple of Core meetings was that Chromium's approach to respect CSS rules prescribed over MathML is the correct one going forward, and that it is desirable for CSS properties to successfully apply to any/all MathML Core elements.

That said, we concretely discussed the `min-width` property, so more nuance may be needed for other cases. If I correctly followed the discussion about combining it with the `stretchy` attribute of an "embellished operator", then the two examples attached below should be expected to succeed stretching to the CSS-prescribed minimal size, when it is applied to the right contextual nodes (rather than the `<mo>` itself). This is already the case by using the current layout algorithm of MathML Core. And is an independent observation from the `minsize`/`maxsize` attribute discussion - both mechanisms inform the layout algorithm.

```html
<math>
  <mi>a</mi>
  <mrow style="min-height:25px"></mrow>
  <mo stretchy="true">↑</mo>
  <mi>b</mi>
</math>

<math>
  <mi>a</mi>
  <munder>
    <mo>→</mo>
    <mrow style="min-width: 25px;"></mrow>
  </munder>
  <mi>b</mi>
</math>
```

Currently it appears that both of these examples stretch correctly in Chrome, and neither stretches in Firefox, for the reasons @ronkok outlined above.
