### ISSUE TITLE
Spacing between two subsequent <mi> elements

### ISSUE THREAD

**Issue by runarberg** [w3c/mathml-core#214]
I noticed that in Firefox when I have two subsequent `<mi>` elements, where the former has more then one character or `mathvariant="normal"` but the latter doesn’t, than there is a small space between them, but in Chrome there isn’t.

![sin x with a little space between sin and x](https://github.com/w3c/mathml-core/assets/3984600/dca61cfc-58e3-4d1d-8abf-34056f0d09cd)
![sin x with no space between sin and x](https://github.com/w3c/mathml-core/assets/3984600/dcd47df5-e811-441b-9659-ecc3c3a1c1a9)

Is the latter behavior the intended behavior the intended one in MathML-Core, and if so, what is the strategy to polyfill the former behavior? It is kind of difficult add padding between them. The only way I can think of is some variation of:

```css
mi[mathvariant="normal"] + mi:not([mathvariant="normal"]) {
  padding-inline-start: 0.35ex;
}
```

However this will fail when the `<mi>` element has more then one character (i.e. implicit normal mathvariant).

**Comment by runarberg** [comment]
Follow up question. Is there a plan to be able to target implicit and explicit normal or italic mathvariants in CSS? For example, something like:

```css
mi:mathvariant(normal) {
  /* matches <mi>sin</mi> and <mi mathvariant="normal">x</mi> */
}

mi:not(:mathvariant(normal)) {
  /* matches <mi>x</mi> */
}
```

**Comment by dginev** [comment]
@runarberg we were just discussing this subtlety in the wikimedia MathML implementation effort, [comment here](https://phabricator.wikimedia.org/T348615#9288127).

I think the lack of spaces is a feature, since it is common to get cases such as `<mi>x</mi><mi>y</mi>` and similar.

There is also a suggestion to put an invisible function application operator between them - `<mo>&#x2061;</mo>`  - which should also aid accessibility. That said, I don't think the Chrome spacing is correct even if that markup is present - unsure if that has to do with the operator dictionary, or is implementation specific.

Today's latexml would emit the following markup [codepen here](https://codepen.io/dginev/pen/wvNxjVq):
```xml
  <mi>sin</mi>
  <mo lspace="0.167em">&#x2061;</mo>
  <mi>x</mi>
```

It's a bit of a curious design, but if you also look at the #209 discussion, an empty-or-invisible operator element between two identifier elements has some broad support.

As to targeting mathvariant - I think  that is less robust long-term than adding a dedicated class attribute in the MathML you are generating, which clearly identifies what the `<mi>` originated from. A `class="trig-function"` is theme-able for many more purposes, and would avoid the defaulting problem.

**Comment by runarberg** [comment]
@dginev I agree, Chrome has the better behavior IMO. I think the invisible operator is an excellent solution. My authoring tool actually includes these (`.$` for invisible function application), but I think I will implicitly add it during parsing before certain identifier tokens (and maybe even before open parenthesis without the lspace attribute for accessibility) if it follows common function identifiers.

Thanks, this answers my question.
