### ISSUE TITLE
English grammar error in 3.1.3

### ISSUE THREAD

**Issue by bert-github** [w3c/mathml-core#224]
In [3.1.3 Anonymous <mrow> boxes](https://www.w3.org/TR/2023/WD-mathml-core-20231127/#anonymous-mrow-boxes), the 2nd paragraph reads

> If a MathML element generates an anonymous <mrow> box if it wraps in children in an anonymous <mrow> box i.e. its subtree in the visual formatting model is made of an [anonymous <mrow> box](https://www.w3.org/TR/2023/WD-mathml-core-20231127/#dfn-anonymous-mrow-box) which itself contains the boxes associated to the children of this MathML element.

There seems to be an ‘if’ too many, the first ‘in’ might be a mistake for ‘its’, and there are probably commas missing before and after ‘i.e.’.

**Comment by davidcarlisle** [comment]
I adjusted the grammar here but didn't close at it's not entirely editorial @fred-wang  can you check the above

**Comment by fred-wang** [comment]
I think this is meant to be the definition for "generates an anonymous mrow box" so it could be the first if removed:

"A MathML element generates an anonymous `<mrow>` box if it wraps in children in an anonymous <mrow> box..."

But I guess the proposal to remove the second if (saying what to do for the subtree rather than what is done) is fine too:

"If MathML element generates an anonymous `<mrow>` box then ..."

Probably I hesitated between the two formulations but either is fine to me.

**Comment by davidcarlisle** [comment]
> either is fine to me.

Ok, thanks, let's call this done.
