### ISSUE TITLE
Block math no longer center aligned?

### ISSUE THREAD

**Issue by faceless2** [w3c/mathml-core#237]
We've been bringing our implementation up to date with changes to the spec over the the last few years, and part of that is adopting the new UA stylesheet.

https://github.com/w3c/mathml-core/commit/18caa77f6b7ff2d03e2b395ba9b8d6648f70e37b removes the `text-align: center` from `<math>` elements with `display="block"`. Is this intentional?

I ask because I can't see it discussed in an issue anywhere, and the checkin comments refer to changes to various examples - makes no mention of changes to the user-agent stylesheet.

The current version of Gecko, Blink, Webkit all center-align block math by default, and `text-align: center` has been a rule going back to MathML2. Removing it makes no difference in Blink or Webkit, both of which seem to ignore `text-align` (sample at https://jsbin.com/dopelav/edit?html,output), but it does change Gecko and our layout engine (BFO Publisher).

**Comment by fred-wang** [comment]
The commit adds explicit text in https://w3c.github.io/mathml-core/#the-top-level-math-element saying block math is horizontally centered:

> Additionally, if the computed display property is equal to block math then that math content box is rendered horizontally centered within the content box. 

Regarding `text-align: center` specifies centering for inline boxes, so relying on that feature does not make sense here (*). I guess the rule was originally copied from internal UA sheet but removed when the centering was made explicit in this commit. See also https://github.com/w3c/mathml-core/issues/156 for a similar issue.

(*) It's not obvious to me why the rule would have any effect on MathML elements, which have their own layout specified in the spec. I suspect the inconsistency between browsers is because of the internal implementations of MathML elements (as block-level or inline-level boxes).

**Comment by faceless2** [comment]
Thanks Fred, I'd missed that in the checkin.

FWIW I'm not sure either - I checked our implementation and it's deliberate but no comment why, so I presume it was a case of "if in doubt, do what Firefox does". Yes there are better ways to do this, eg `width:min-content; margin-right: auto`
