### ISSUE TITLE
Missing autofocus attribute for MathML elements

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#258]
From https://w3c.github.io/mathml-core/#dom-and-javascript we override the HTMLOrForeignElement

which is still called HTMLOrSVGElement in HTML5:

https://html.spec.whatwg.org/multipage/dom.html#htmlorsvgelement
https://github.com/whatwg/html/pull/5248

which has IDL attributes dataset (for data-*), nonce, autofocus and tabIndex (for tabindex).

But from https://w3c.github.io/mathml-core/#attributes-common-to-html-and-mathml-elements I can't see where we define a content attribute autofocus  for MathML.

(note: found while checking Gecko code here: https://searchfox.org/mozilla-central/rev/4a8bd8efdfaa43dd14a16d3cb15bf86796fd1def/dom/mathml/MathMLElement.h#87)

**Comment by davidcarlisle** [comment]
You suggest we fix by adding the attribute?

**Comment by fred-wang** [comment]
Right, I think in this list

> The id, class, style, data-*, nonce and tabindex attributes have the same syntax and semantics as defined for [id](https://w3c.github.io/mathml-core/#dfn-id), [class](https://w3c.github.io/mathml-core/#dfn-class), [style](https://w3c.github.io/mathml-core/#dfn-style), [data-*](https://html.spec.whatwg.org/#embedding-custom-non-visible-data-with-the-data-*-attributes), [nonce](https://w3c.github.io/mathml-core/#dfn-nonce) and [tabindex](https://w3c.github.io/mathml-core/#dfn-tabindex) attributes on HTML elements.

**Comment by davidcarlisle** [comment]
I could do that (and update the schema at same time) Probably we'll want to add to full as well so full is a superset of core (I'll raise at the full meeting tonight)
I'll make a PR later

**Comment by fred-wang** [comment]
OK thank you.

I assume this only has an effect on elements with a href or tabindex, so that's related to other pending discussions though.

**Comment by davidcarlisle** [comment]
yes i was wondering about that, but it seems that if we follow html we make it globally available with same semantics as html and if that's nothing in some cases so be it (rather than trying to enumerate where it is used?)

**Comment by davidcarlisle** [comment]
sigh I messed up the commit log ref but https://github.com/w3c/mathml-schema/commit/74a8d2c8efe64f5d55676aaf2e75189c5249cebe

**Comment by davidcarlisle** [comment]
@fred-wang  I think this is done (here and in the schema which shows in the mathml full spec) 

I think there is an issue with the refspec markup in that I think the links in section 2.1.4 https://w3c.github.io/mathml-core/#attributes-common-to-html-and-mathml-elements ought (like `data-*`) go to the definitions in html rather than back to the same section, but that applies to the existing tabindex and nonce attribute markup as well, so I think this can be closed.

I pushed to main rather than make  PR as it seems non controversial and essentially trivial change in the spec text.

Please close here if you are happy with this change (I may look at the refspec markup later: the intention of `[^htmlsvg-global/tabindex^]` was to reference a different spec as determined by the refspec lookup, but that seems not to be happening)

**Comment by davidcarlisle** [comment]
Closing after call today
