### ISSUE TITLE
MathML-Core Meeting Monday, November 25, 2024

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#269]
Let's focus on the issues that are labelled 118n-needs-resolution first, so that we can advance.  

* Define that (and how) glyph assemblies are mirrored in rtl formulas #235 

* Explain the mapping tables (appendix C)  #234  

* Whether/when to mirror operators #233 (Note: level 2) 

*  lspace/rspace have confusing names i18n-needs-resolution #232

**Comment by dginev** [comment]
- Could we dsicuss which characters can reliably work with `<mover>` accents, and where they could be listed?  
   -  #254

**Comment by davidcarlisle** [comment]
I may be travelling, I should be able to make the call, but don't wait if I'm not there.

**Comment by ljmaher** [comment]
Thanks Brian.



Regards
Louis Maher
Phone: 713-444-7838
Email: ***@***.***

From: Brian Kardell ***@***.***>
Sent: Friday, November 22, 2024 2:11 PM
To: w3c/mathml-core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [w3c/mathml-core] MathML-Core Meeting Monday, November 25, 2024 (Issue #269)


Let's focus on the issues that are labelled 118n-needs-resolution first, so that we can advance.

  *   Define that (and how) glyph assemblies are mirrored in rtl formulas #235<https://github.com/w3c/mathml-core/issues/235>
  *   Explain the mapping tables (appendix C) #234<https://github.com/w3c/mathml-core/issues/234>
  *   Whether/when to mirror operators #233<https://github.com/w3c/mathml-core/issues/233> (Note: level 2)
  *   lspace/rspace have confusing names i18n-needs-resolution #232<https://github.com/w3c/mathml-core/issues/232>

-
