### ISSUE TITLE
Include mo@accent attribute into MathML Core?

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#52]
This is a follow-up of https://github.com/mathml-refresh/mathml/issues/151 and https://github.com/mathml-refresh/mathml/issues/76 and https://github.com/mathml-refresh/mathml/issues/164

mo@accent duplicates what is provided by munderover's accent attribute and violates the CSS logic of having properties depending on parents not on arbitrary descendants. As I said elsewhere I think it should just be removed and not implemented in Chromium.

I'm just opening this to put the ISSUE label on the spec.

**Comment by fred-wang** [comment]
There is no plan to implement mo@accent in Chromium's initial implementation. Instead, we implemented the accent/accentunder attributes on underover scripts described in the spec. I think discussion should be postpone for level 2.

**Comment by NSoiffer** [comment]
Here's Chrome Canary's rendering (19/2/22; V 99.9.4840.0) of the above (same [codepen ](https://codepen.io/nms/pen/bGpQjmP)as above but with the scripting for MathJax removed):
![image](https://user-images.githubusercontent.com/1545836/150274956-baf5e7cd-76e3-4d0d-9bc5-b772b6b5a16e.png)

Clearly the Chrome implementation doesn't (yet) implement the accent property's positioning regardless of where it is set or inherits from. Also missing from the implementation is horizontal stretching, but that's a separate feature.

As already discussed, removing this feature from Core is a breaking change to common/everyday MathML. As such, it [violates one the charter's tenets](https://www.w3.org/Math/Documents/Charter2021.html#out-of-scope).

**Comment by dginev** [comment]
> Almost all WYSIWYG editors and TeX converters today don't use the accent property on mover, etc. So virtually all use of accents would break.

For `\hat{a}`, one gets:
1. `<mover accent="true">` with no accent attribute on the `<mo>` in:
     - latexml, katex, tralics, 

2. mover and mo with no accent attribute anywhere:
     - mathjax, 
 
3. pure unicode â, no MathML:
    - pandoc, tex4ht

4. `<mover>` with an `<mo accent="true">`
     - pandoc, tex4ht - for larger bases (e.g. `a+b`) and explicitly requested mathml output


Some of the modern converters just delegate to the polyfills (asciimath, lwarp), and some of the old ones still generate images (latex2html). I have no idea about the Windows-only toolchains.

Just dropping a comment, since I found the claim that "almost all TeX converters today don't use the accent property on mover" a bit odd, when three of them do.  Clearly this is a decision with some complex trade-offs. I wonder if it's worth reaching out to the pandoc and tex4ht teams and asking them if they can transition smoothly?

**Comment by bkardell** [comment]
Discussed on the call today, resolved to  contact the MathJax team and see if they are able to generate accent=true on mover for some day in the future when there is a MathML-Core output support.  (Neil will take the action). If they are willing to do that (as they are ~95% of the output), then we will remove accent on the mo in the spec as suggested in the issue. A secondary issue can be opened in full.

**Comment by NSoiffer** [comment]
FYI: I checked MathType and it uses `accent` on `mover`. Murray did the same for Word's editor and found the same.

**Comment by NSoiffer** [comment]
I heard from David Cervone (MathJax) that they are able to generate accent=true on mover for some day in the future.

Closing because this was the condition that was the remaining issue to accepting it.
