### ISSUE TITLE
Define if width/height/inline-size/block-size are supported.

### ISSUE THREAD

**Issue by bfgeek** [w3c/mathml-core#75]
A simple test case:
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=6693

Safari appears to support height at least on the <math> element, however firefox appears not to?

From an implementation POV it may be easier just to support all width/height/etc on all elements, however this gets into how to define the internal MathML algorithms.

On the <math> element this needs tests for various values of width/height, and within various formatting contexts, e.g. flex (does it respect flex-basis properly), grid, etc.

**Comment by fred-wang** [comment]
A use case was mentioned at BlinkOn:
https://www.youtube.com/watch?v=n9lX5RLWwGs (table discussion starts at 8:53)

https://people.igalia.com/fwang/2022-blinkon-16-remainder-estimate-for-mathml-integration/#/18
https://people.igalia.com/fwang/2022-blinkon-16-remainder-estimate-for-mathml-integration/#/19

Basically, it would be good to resolve "width: auto" to "fit-content" for `<mtd>` cells otherwise block children take the available size which we don't want. Maybe we actually want that for all MathML elements with math display too.

**Comment by davidcarlisle** [comment]
@fred-wang   nice presentation, thanks

**Comment by fred-wang** [comment]
We still have inconsistencies between tests VS browsers VS spec. My plan is to resolve this by aligning as much as possible on what Rob has implemented for Chrome.

I'll start with adding a universal rule `* { overflow: hidden !important; }` to ignore overflow. That generalizes what Rob implemented for mspace and will make discussion/specification/implementation easier (see my C above).

**Comment by fred-wang** [comment]
> We still have inconsistencies between tests VS browsers VS spec. My plan is to resolve this by aligning as much as possible on what Rob has implemented for Chrome.

This is what I discussed with @bfgeek at BlinkOn. I'm going to provide more analysis, but I'm already attaching a test case that can be tried in Chrome 109.

> I'll start with adding a universal rule * { overflow: hidden !important; } to ignore overflow. That generalizes what Rob implemented for mspace and will make discussion/specification/implementation easier (see my C above).

At the end, I think it's probably better to keep overflow. Hopefully, we only need to explain how width & height affect layout and refer to the proper CSS spec about how overflow affects rendering, scrollbars etc.  Rob's rule was removed in https://chromium-review.googlesource.com/c/chromium/src/+/4043023 and a test to check that the property can be overridden has been added.

**Comment by NSoiffer** [comment]
I would have thought that it should behave similarly to using `mpadded`. However, the following MathML ([codepen](https://codepen.io/nms/pen/oNyVJxR)):
```
<math>
  <mpadded style="background-color: red;" width="3em">
    <mtext>1234567890</mtext>
    <mi>A</mi>
  </mpadded>
</math>
```

doesn't work as I expected. According to my reading of the spec, the "A" should overlap the non-red part of the `mtext`, but instead, it occurs at the end:  ![image](https://user-images.githubusercontent.com/1545836/206602369-be3d1dad-3b45-4d61-849c-c87e6ba3cc96.png).

Note: Chrome (canary) renders the same as Firefox.

**Comment by dginev** [comment]
@NSoiffer I'm curious, doesn't the behavior you described in words belong to the case where the `A` is a sibling to the mpadded, rather than a last child? It is exactly what is currently rendered with:
```xml
<math>
  <mpadded style="background-color: red;" width="3em">
    <mtext>1234567890</mtext>
  </mpadded>
  <mi>A</mi>
</math>
```

In your snippet where the `A` is inside the mpadded, I think the expected overflow behavior should kick in (if/when that is formally decided). Currently, if I set `overflow: hidden;` on the mpadded, and the `A` is inside, it gets hidden, together with the overflowing portion of the mtext. Which seems correct?

**Comment by NSoiffer** [comment]
In messing around with the codepen, I somehow made it different than the example shown. Changing it to the example shown does result in the expected behavior in both Chrome and Firefox: ![image](https://user-images.githubusercontent.com/1545836/206766178-c8662154-a5f9-460a-b11d-824540751509.png) Sorry about the mistake.

Also, that behavior is what I would expect with `overflow:visible`. For `overflow:hidden` I would expect it to be clipped which it is in Chrome canary but not in Firefox. My two wrongs did not make a right :-(

**Comment by fred-wang** [comment]
It looks like I failed to attach the testcase the other day, I'm pasting the source again below together with the detailed explanation.

I understand from previous discussions that people don't have strong opinion about what the "right" behavior should be. So my proposal is to follow Chromium here, add missing bits into the spec and update tests accordingly. WebKit/Firefox may implement things differently but their choices were probably not made on purpose, and they should eventually be aligned with MathML Core (the same is true for other CSS properties like padding/border/margin, float, etc).

Testcase:

```
<!DOCTYPE html>
<style>
  .el {
      border: 1px solid red;
      overflow: hidden /* scroll; */;
  }
  math {
      font-size: 100px;
  }
  .gradient {
      background: linear-gradient(to bottom right, blue, pink);
  }
</style>
<h1>MathML width/height</h1>

<h2><a href="https://w3c.github.io/mathml-core/#text-mtext">mtext</a></h2>

<p>
  <math>
    <mtext class="el">XX</mtext>
    <mtext class="el" style="width: 200px; height: 200px;">XX</mtext>
    <mtext class="el" style="width: 50px; height: 50px;">XX</mtext>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#text-mspace">mspace</a></h2>

<p>
  <math>
    <mspace class="el">
      <mtext>XX</mtext>
    </mspace>
  </math>
  <math>
    <mspace class="el" style="width: 200px; height: 200px;">
      <mtext>XX</mtext>
    </mspace>
  </math>
  <math>
    <mspace class="el" style="width: 50px; height: 50px;">
      <mtext>XX</mtext>
    </mspace>
  </math>
</p>

<p>
  __<math>
    <mspace class="el gradient" width="100px" height="50px" depth="50px">
    </mspace>
  </math>
  <math>
    <mspace class="el gradient" width="100px" height="50px" depth="50px" style="width: 200px; height: 200px">
      <mtext>XX</mtext>
    </mspace>
  </math>
  <math>
    <mspace class="el gradient" width="100px" height="50px" depth="50px" style="width: 50px; height: 50px">
      <mtext>XX</mtext>
    </mspace>
  </math>__
</p>

<h2><a href="https://w3c.github.io/mathml-core/#horizontally-group-sub-expressions-mrow">mrow</a></h2>

<p>
  <math>
    <mrow class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mrow>
    <mrow class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mrow>
    <mrow class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mrow>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#fractions-mfrac">mfrac</a></h2>

<p>
  <math>
    <mfrac class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mfrac>
    <mfrac class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mfrac>
    <mfrac class="el" style="width: 20px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mfrac>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#radicals-msqrt-mroot">msqrt, mroot</a></h2>

<p>
  <math>
    <msqrt class="el">
      <mtext>X</mtext>
    </msqrt>
  </math>
  <math>
    <msqrt class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
    </msqrt>
  </math>
  <math>
    <msqrt class="el" style="width: 100px; height: 100px;">
      <mtext>X</mtext>
    </msqrt>
  </math>
</p>

<p>
  <math>
    <mroot class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mroot>
  </math>
  <math>
    <mroot class="el" style="width: 300px; height: 300px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mroot>
  </math>
  <math>
    <mroot class="el" style="width: 100px; height: 100px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mroot>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#adjust-space-around-content-mpadded">mpadded</a></h2>

<p>
  <math>
    <mpadded class="el">
      <mtext>XX</mtext>
    </mpadded>
  </math>
  <math>
    <mpadded class="el" style="width: 200px; height: 200px;">
      <mtext>XX</mtext>
    </mpadded>
  </math>
  <math>
    <mpadded class="el" style="width: 50px; height: 50px;">
      <mtext>XX</mtext>
    </mpadded>
  </math>
</p>

<p>
  __<math>
    <mpadded class="el gradient" width="100px" height="50px" depth="50px">
    </mpadded>
  </math>
  <math>
    <mpadded class="el gradient" width="100px" height="50px" depth="50px" style="width: 200px; height: 200px">
      <mtext>XX</mtext>
    </mpadded>
  </math>
  <math>
    <mpadded class="el gradient" width="100px" height="50px" depth="50px" style="width: 50px; height: 50px">
      <mtext>XX</mtext>
    </mpadded>
  </math>__
</p>

<h2><a href="https://w3c.github.io/mathml-core/#subscripts-and-superscripts-msub-msup-msubsup">msub, msup, msubsup</a></h2>

<p>
  <math>
    <msub class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msub>
    <msub class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msub>
    <msub class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msub>
  </math>
</p>

<p>
  <math>
    <msup class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msup>
    <msup class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msup>
    <msup class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msup>
  </math>
</p>

<p>
  <math>
    <msubsup class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msubsup>
    <msubsup class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msubsup>
    <msubsup class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </msubsup>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#underscripts-and-overscripts-munder-mover-munderover">munder, mover, munderover</a></h2>

<p>
  <math>
    <munder class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </munder>
    <munder class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </munder>
    <munder class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </munder>
  </math>
</p>

<p>
  <math>
    <mover class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mover>
    <mover class="el" style="width: 200px; height: 200px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mover>
    <mover class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mover>
  </math>
</p>

<p>
  <math>
    <munderover class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </munderover>
    <munderover class="el" style="width: 300px; height: 300px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </munderover>
    <munderover class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </munderover>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#prescripts-and-tensor-indices-mmultiscripts">mmultiscripts</a></h2>

<p>
  <math>
    <mmultiscripts class="el">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mprescripts/>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mmultiscripts>
    <mmultiscripts class="el" style="width: 300px; height: 300px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mprescripts/>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mmultiscripts>
    <mmultiscripts class="el" style="width: 50px; height: 50px;">
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mtext>X</mtext>
      <mprescripts/>
      <mtext>X</mtext>
      <mtext>X</mtext>
    </mmultiscripts>
  </math>
</p>

<h2><a href="https://w3c.github.io/mathml-core/#tabular-math">Tabular elements</a></h2>

<p>This should be covered by other CSS spec.</p>
```

Chromium implementation:

- mtext layout: Uses the specified width/height. The inline/block-start edges of the ink bounding box of the text are aligned with the inline/block-start edges of the element.

- mspace layout: Children in the DOM don't show up in the layout tree. The width attribute is mapped to the width property, the height/depth attribute are mapped to the height property, the height attribute is used as an internal baseline. These presentational hints can be overridden by specifying width/height attributes.

- mrow layout: Uses the specified width/height. The inline/block-start edges of the content are aligned with the inline/block-start edges of the element.

- mfrac layout: Uses the specified width/height. The block-start edge of the content is aligned with the block-start edges of the element. The middle of the inline edge of the content is aligned with the middle of the inline edge of the element. The fraction bar uses the width of the element.

- msqrt/mroot layout: Uses the specified width/height. The inline/block-start edges of the content are aligned with the inline/block-start edges of the element.

- mpadded layout: height/depth/lspace/voffset attributes are mapped to internal properties. width attribute is mapped to the width property, but can be overridden by the user. Specifying the height property has no effect.

- msub/msup/msubsup: Uses the specified width/height. The inline/block-start edges of the content are aligned with the inline/block-start edges of the element.

- munder/mover/munderover: Uses the specified width/height. The block-start edge of the content is aligned with the block-start edges of the element. The middle of the inline edge of the content is aligned with the middle of the inline edge of the element. 

- mmultiscripts: Uses the specified width/height. The inline/block-start edges of the content are aligned with the inline/block-start edges of the element.

- tabular elements: They use non-math display values are interaction with width/height is specified by other specifications.

More notes:

- As a general rule of thumb, Chromium follows (2)(3)(4) from https://github.com/w3c/mathml-core/issues/75#issuecomment-511718819 ; for (1) let's move discussion to #76 and #77
- A different overflow value should work, in particular those adding scrollbars. I assume this is specified in other CSS specs once the bounding boxes are well-defined and positions are well-defined, so nothing more to do in MathML Core.
- For mfrac/munder/mover/munderover, the choice during review was to make content centered on the inline-axis, for consistency with other similar layout like flexbox and to make calculation simple. Probably, the same rationale happens for the width of the fraction bar.
- For mspace/mpadded, they have special implementations of sizing attributes so the interaction with width/height property is a bit less straightforward. That the height property is ignored is probably a bug, though will double-check with Ian.

**Comment by fred-wang** [comment]
## More details of Chrome's current implementation for mspace/mpadded

### mspace width/height

- If width attribute present, add corresponding presentation hint in order to set width property accordingly.
- If both height and depth attributes nonempty, add corresponding presentation hint in order to set height property to calc(height value + depth value).
- Otherwise, if one of height and depth attribute is nonempty, add corresponding presentation hint in order to set height property accordingly.
- If height parses to length-percentage, use it for an internal baseline property.

### mpadded width/height

- If width attribute present and is not a percent, add corresponding presentation hint in order to set width property accordingly.
- If height parses to length value (not percentage), use it for an internal baseline property.
- If depth parses to length value (not percentage), use it for an internal depth property.
- If lspace parses to length value (not percentage), use it for an internal lspace property.
- If voffset parses to length value (not percentage), use it for an internal voffset property.

### Observations

Because mspace relies only on presentation hints, it's possible to specify width/height properties to the ones calculated from the attributes. For mpadded, this is only possible for the width property. The layout ignores the height property and will always use the sum of internal baseline and internal depth.

IIUC, @rwlbuis initially tried to make mpadded do the same calc trick as for mspace but the difference is that mspace does not have children, so its default height/depth values are always 0. However, a simple mpadded like `<mpadded height="50px"><mspace depth="30px"/></mpadded>` should have the depth=30px of the child and the height=50px specified in its attribute, which makes calculation trickier.

In addition, in MathML 3 mpadded percentage values should be treated relative to the content size e.g. `<mpadded height="200%"><mspace height="10px"></mspace></mpadded>` would have height=20px. But that's not really how CSS works and won't work with presentational hints above. So Chromium just treats percentage values for mpadded attributes as invalid.

### Ideas for improvements

(1) Add `mpadded { height: auto !important; }` in the UA sheet since (according to @bfgeek) a general rule is that it is not ok to ignore width/height during layout.

(2) If we think handling of width/height is inconsistent in mpadded, handle mpadded@width as an internal property and force `mpadded { width: auto !important; }`. Otherwise the spec should mention the presentation hint used.

(3) If additionally we think handling of mpadded/mspace is inconsistent, implement mspace using internal properties and force width/height to auto in UA sheet. Otherwise, the spec should mention the presentation hints used.

(4) MathML Core should which values percentages are resolved against. For mspace, it says they are treated as zero but that's missing for mpadded. Level 1 should probably say percentages values are invalid.

Besides inconsistency, an annoying aspect with Chrome's implementation is that it is less clear whether absent/invalid/<length-percentage>/negative values are handled as described in [mspace](https://w3c.github.io/mathml-core/#dfn-mspace) and [mpadded](https://w3c.github.io/mathml-core/#inner-box-and-requested-parameters) sections, which might be one rationale to move to internal properties instead. Or otherwise we can try to parse the value before setting the presentational hint.

**Comment by brucemiller** [comment]
Thanks for the clarifications @fred-wang.

I don't want to hijack a perfectly good thread, but this has me wondering if the relative dimensions of MathML Full (eg. `<mpadded width="-0.222em">...` to *reduce* the width)  could be recovered by mapping them to some internal form of CSS padding (although it would need to allow negative values).

You might think it easy enough to calculate the effective final width of such a construct, but in practice it's rather difficult & unreliable in a MathML generator targeting an unknown user agent with unknown fonts.

If this is worth discussing, but doesn't fit this thread, I can open a separate Issue.

**Comment by fred-wang** [comment]
> For mspace/mpadded, they have special implementations of sizing attributes so the interaction with width/height property is a bit less straightforward. That the height property is ignored is probably a bug, though will double-check with Ian.

Now checking the layout side of the mpadded implementation, that indeed seems a bug: it seems possible to take into account the CSS height property, after having calculating the content size from the height/depth attributes. I uploaded https://chromium-review.googlesource.com/c/chromium/src/+/4116578 for that purpose. seems a nicer solution than the `mpadded { height: auto !important; }` thing I mentioned above. That way all MathML elements would accept width/height, with some special behavior for mfrac/munder/mover/munderover/mspace/mpadded mentioned above.

**Comment by fred-wang** [comment]
I landed the change to make Chromium takes into account the `<mpadded>` height this morning.

As I mentioned above, the fraction bar takes the full inline size of the content box, rather than the maximum of the numerator/denuminator inline sizes ; which makes a difference if one specify the width of the content box as in the testcase above. I understand this is to avoid passing extra information to the painter code, which makes implementation a bit more simple. I guess we can do that for MathML Core level 1, but can be changed in the future if people believe it's worth it.

Finally, Chromium also supports padding/border/margin/box-sizing properties on MathML elements, it's interesting to play with them on the test case and check they behave as expected.

Will draft a PR to align with Chromium's behavior.

**Comment by fred-wang** [comment]
https://github.com/w3c/mathml-core/pull/184 is now ready for review.

@rwlbuis Since you are the one who originally implemented mspace/mpadded in Chrome, can you please the text? Thanks!

**Comment by fred-wang** [comment]
> #184 is now ready for review.
> 
> @rwlbuis Since you are the one who originally implemented mspace/mpadded in Chrome, can you please the text? Thanks!

Just got approval from rob and no opposition for 2 weeks, so I guess I'll merge this PR and update WPT tests accordingly.

**Comment by fred-wang** [comment]
This is merged. I'll close this issue when tests are updated.

**Comment by fred-wang** [comment]
We have minimal test coverage after these PR, so closing:

https://github.com/web-platform-tests/wpt/pull/38361
https://github.com/web-platform-tests/wpt/pull/38443
https://github.com/web-platform-tests/wpt/pull/38466
